### ISSUE TITLE
issue in inference

### ISSUE THREAD

**Issue by mohamedmossadaeye** [li-plus/DSNet#11]
python infer.py anchor-based --ckpt-path ../models/custom/checkpoint/custom.yml.0.pt \
                             --source ../custom_data/videos/EE-bNr36nyA.mp4 --save-path ./output.mp4
Loading DSNet model ...
Traceback (most recent call last):
  File "infer.py", line 66, in <module>
    main()
  File "infer.py", line 18, in main
    model.load_state_dict(state_dict)
  File "/home/mossad/aeye/DSNet/venv/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1407, in load_state_dict
    self.__class__.__name__, "\n\t".join(error_msgs)))
RuntimeError: Error(s) in loading state_dict for DSNet:
        Unexpected key(s) in state_dict: "fc_ctr.weight", "fc_ctr.bias".

**Comment by mohamedmossadaeye** [comment]
sorry , my bad , i trained model using anchor-free option and tried to infer with option anchor-based
